platform :ios, '10.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative'../node_modules/react-native-unimodules/cocoapods.rb' 

target 'aelfAccount' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'aelfAccountTests' do
    inherit! :complete
    # Pods for testing
  end

  use_unimodules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'aelfAccount-tvOS' do
  # Pods for aelfAccount-tvOS

  target 'aelfAccount-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
