# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "aelfAccount.xcodeproj")
    build_app(workspace: "aelfAccount.xcworkspace", scheme: "aelfAccount")
    upload_to_app_store
  end

  desc "Push a new release build to the firm"
  lane :fir_im do
    sync_code_signing(
      type: "adhoc",
      # readonly: true,
      force_for_new_devices: true,
      app_identifier: ["com.aelf.aelfAccount"],
    )
    gym(
      scheme: "aelfAccount",
      export_method: "ad-hoc",
      silent: true,  # 隐藏没有必要的信息
      clean: true,  # 在构建前先clean
    )
    # update to fir.im
    fir_cli(
      api_token: "",
      short: "iosaelfAccount",
      changelog: "Hello aelf",
      dingtalk_access_token: "",
    )
  end

    desc "Push to telegram"
    lane :push_telegram do
      version_name = get_version_number(
        xcodeproj: "aelfAccount.xcodeproj",
        target: "aelfAccount"
        )
      version = sh( "../../fastlane_version.sh ios");
      UI.message("final version: " + version + version_name )
      telegram(
        token: "",
        chat_id: "",
        text: "http://d.firim.vip/iosaelfAccount " + "aelfaccount-" + version_name + " iOS Build" + version,
        proxy: "http://127.0.0.1:1087"
      )
    end
end
